sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - udf_coverage
      - jar_artifact
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: false
  exasolDbVersions:
    - "8.31.0"
    - "7.1.29"
linkReplacements:
  - https://developers.google.com/protocol-buffers/protobuf-java/|https://developers.google.com/protocol-buffers
