sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - udf_coverage
      - jar_artifact
build:
  freeDiskSpace: false
  exasolDbVersions:
    - "8.34.0"
    - "7.1.30"