sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - udf_coverage
      - jar_artifact
excludes:
  - "E-PK-CORE-18: Outdated content: '.github/workflows/broken_links_checker.yml'"
linkReplacements:
  - https://developers.google.com/protocol-buffers/protobuf-java/|https://developers.google.com/protocol-buffers
